services:
  backend:
    build: ./weather-app-backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./weather-app-backend:/backend/code
    ports:
      - "8000:8000"
  frontend:
    build: ./weather-app-frontend/
    command: npm start
    volumes:
      - ./weather-app-frontend:/frontend/code
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - backend