# Generated by Django 4.2.10 on 2024-02-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_city_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
