# Generated by Django 4.2.10 on 2024-02-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userid_city_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['state']},
        ),
        migrations.AlterModelOptions(
            name='userid',
            options={'ordering': ['userId']},
        ),
        migrations.AddField(
            model_name='userid',
            name='cities',
            field=models.ManyToManyField(to='dashboard.city'),
        ),
    ]
