# Generated by Django 4.2.10 on 2024-02-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_city_options_alter_userid_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userid',
            name='cities',
            field=models.ManyToManyField(blank=True, default='', to='dashboard.city'),
        ),
    ]
