# Generated by Django 4.2.10 on 2024-02-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_userid_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='city',
            name='feels_like',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='temp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='temp_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='temp_min',
            field=models.FloatField(default=0),
        ),
    ]
